### PR TITLE
Leftover cleanups

### PR DESCRIPTION
**Pull request by oleorhagen**
Plus a few leftover cleanups

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
Please update the PR title.

Sorry for the noise going back and forth, I didn't get in advance that this would affect both GO and Python...

**Review by lluiscampos — CHANGES_REQUESTED** [review]
You have to update [LICENSE](https://github.com/mendersoftware/mendertesting/blob/master/LICENSE) to 2021. This is technically the first 2021 PR in this repo.

**Comment by oleorhagen** [comment]
Yes, yes.. on it...

**Comment by lluiscampos** [comment]
> You have to update [LICENSE](https://github.com/mendersoftware/mendertesting/blob/master/LICENSE) to 2021. This is technically the first 2021 PR in this repo.

CI still failing, some other fixes around licenses. Let's fix everything in this PR please :)

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
