### PR TITLE
Set checksum filepath to default value

### PR DESCRIPTION
**Pull request by alfrunes**
Made it possible to modify the CHKSUM_FILE variable if it's defined in
the environment.

Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
What's the motivation for this change? This looks a bit "debug-gy" to me.

**Comment by alfrunes** [comment]
I moved the `LIC_FILES_CHKSUMS.sha256` away from the root directory in `mender` [#439](https://github.com/mendersoftware/mender/pull/439) into the `vendor` directory.

**Comment by kacf** [comment]
Why? I would prefer not to change this as it is standard in all our Go, and Yocto expects it in this location as well.

**Comment by alfrunes** [comment]
You're right. I was just trying to move as many "unneeded" files from the root directory in the `mender` repository for esthetic reasons :). However, if Yocto depends on this file location I'll revert these changes and close this PR.

**Pull request closed without merging**
