### PR TITLE
Master

### PR DESCRIPTION
**Pull request by maciejmrowiec**

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
Looks like I had some older commits waiting for PR - empty test to get right coverage, some extras to travis and make checksum tests run on dawrin

**Comment by maciejmrowiec** [comment]
@kacf

**Comment by kacf** [comment]
This should probably be rebased, a lot of merge commits here, and you need to sign off the commits, otherwise looks good to me.

**Comment by maciejmrowiec** [comment]
removed that old commits - makes it's simples to stick to one thing I wanted to contribute at the moment

**Comment by maciejmrowiec** [comment]
thanks

**Pull request merged**
